name: 'Start Torque Sandbox'
description: 'Starts a sandbox in Torque and returns its details'
author: 'Quali'
inputs:
  space:
    description: 'The Torque space to start the sandbox in'
    required: true
  blueprint_name:
    description: 'The name of the Blueprint to use'
    required: true
  sandbox_name:
    description: 'Provide a name for the Sandbox'
    required: false
    default: gh-build-${{ github.repository }}
  torque_token:
    description: 'A Torque longterm token'
    required: true
  torque_hostname:
    description: 'Alternative Torque server url'
    required: false
    default: portal.qtorque.io
  branch:
    description: 'Use the Blueprint version from a remote Git branch'
    required: false
    default: ""
  duration:
    description: 'The Sandbox will automatically de-provision at the end of the provided duration (minutes)'
    required: false
    default: '120'
  timeout:
    description: 'Set the time (minutes) to wait for the sandbox to become active. When setting to 0 the action will end with just the sandbox ID output.'
    required: false
    default: 0
  inputs:
    required: false
    description: 'A comma-separated list of key=value pairs. For example: key1=value1, key2=value2'
    default: ""

outputs:
  sandbox_id:
    description: 'The ID of launched Torque Sandbox'
  sandbox_details:
    description: 'The Full sandbox details in a json format'

runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ${{ inputs.blueprint_name }}
    - ${{ inputs.sandbox_name }}
    - ${{ inputs.branch }}
    - ${{ inputs.duration }}
    - ${{ inputs.timeout }}
    - ${{ inputs.inputs }}

  env:
    TORQUE_TOKEN: ${{ inputs.torque_token }}
    TORQUE_SPACE: ${{ inputs.space }}
    TORQUE_HOSTNAME: ${{ inputs.torque_hostname }}
        
branding:
  icon: 'play-circle'  
  color: 'blue'
